# Generated by Django 4.0.5 on 2024-01-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_projects_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.TextField(default='none'),
        ),
    ]
