# Generated by Django 4.0.5 on 2024-01-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_projects_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='use_cases',
            field=models.TextField(default='none'),
        ),
    ]
