# Generated by Django 5.1.1 on 2025-01-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_projects_use_cases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='imageCover',
            new_name='imageCover_large',
        ),
        migrations.AddField(
            model_name='projects',
            name='imageCover_small',
            field=models.TextField(default='none'),
        ),
    ]
