# Generated by Django 5.1.1 on 2025-01-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_rename_imagecover_projects_imagecover_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='has_video',
            field=models.TextField(default='none'),
        ),
    ]
